### ISSUE TITLE
Hackathon dari Alcatel Lucent

### ISSUE THREAD

**Issue by pascalalfadian** [ProIfUNPAR/train-tracker-ellena-angelica#1]
Halo @EllenaAngelica & team,

Ini ada info hackathon, hadiah pertama nya jalan2 ke Paris. Siapa tahu tertarik. Saya hanya tawarkan ke top team di ProIf kemarin.

![img_2099](https://user-images.githubusercontent.com/5976057/40951967-982e97c4-68a3-11e8-9a12-085d80d2fc0d.JPG)

Saya sempat googling soal Rainbow API, sepertinya yang ini: https://hub.openrainbow.com/#/mobiles

Trims.

**Comment by EllenaAngelica** [comment]
Selamat siang Pa Pascal,

Terima kasih atas tawarannya. Sebelumnya kami ada pertanyaan. Kegiatan
Hackathon ini apa saja? Aplikasi android yang di apply aplikasi train
tracker yang dimodifikasikan ke rainbow platform atau buat aplikasi android
baru?

Salam,

Ellena Angelica

Pada tanggal Sel, 5 Jun 2018 09:35, Pascal <notifications@github.com>
menulis:

**Comment by pascalalfadian** [comment]
Hackathon itu biasanya 24 jam coding, tetapi untuk yang ini terus terang saya tidak baca detail. Aplikasi yang dibuat tentu saja baru, terkait topik dan API yang diwajibkan di sana.
